version: "3.3"

services:
  buscador-mongo:
    container_name: "mongodb"
    image: mongo
    ports:
      - 27017:27017
  buscador-selenium:
    container_name: "firefox"
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
  pasionaria-db:
      container_name: "pasionaria-db"
      image: postgres:alpine3.17
      environment:
        - POSTGRES_PASSWORD=homito
      ports:
        - 6500:5432
