version: "3.3"

services:
  pasionaria-db:
      container_name: "pasionaria-db"
      image: postgres:alpine3.17
      environment:
        - POSTGRES_PASSWORD=homito
      ports:
        - 6500:5432
      volumes:
        - backup_db:/backup
volumes:
  backup_db:
    driver_opts:
      type: none
      device: ~/backup/postgres
      o: bind