version: "3.8"
services:
#  buscador-ui: es el proyecto de Angular
  buscador-ui:
    image: front-parcial:1.34-dev
    ports:
      - 4200:80
    networks:
      pasionaria_network:
        aliases:
          - buscador-ui
    depends_on:
      - buscador-api
  # es una imagen de postgresql para almacenar toda la data referida al proyecto y que sigue una estructura en concreto
  buscador-db:
    image: postgres:alpine3.17
    environment:
      - POSTGRES_PASSWORD=homito
    ports:
      - 6500:5432
    networks:
      pasionaria_network:
        aliases:
          - buscador-db
    volumes:
      - backup_db:/backup
#  buscador-api: es el proyecto Java Spring Boot
  buscador-api:
    image: back-parcial:1.34f1
    ports:
      - 8080:8080
    volumes:
    - resources:/resources
    environment:
#      postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://buscador-db/pasionaria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: homito
    networks:
      pasionaria_network:
        aliases:
          - buscador-api
    depends_on:
      - buscador-db
networks:
  pasionaria_network:
    name: pasionaria_net
    driver: bridge
    ipam:
      driver: default
      
volumes:
  resources:
    driver_opts:
      type: none
      device: /resources
      o: bind
  backup_db:
     driver_opts:
       type: none
       device: /home/homitowen/backup/postgres/
       o: bind
  
  
  
  
  