version: "3.8"
services:
#  buscador-ui: es el proyecto de Angular
  buscador-ui:
    image: front-parcial:1.2
    ports:
      - 4200:80
    networks:
      pasionaria_network:
        aliases:
          - buscador-ui
    depends_on:
      - buscador-api
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 50M
        reservations:
          cpus: 0.25
          memory: 50M
  # es una imagen base de mongo para almacenar algunos datos
  buscador-mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      pasionaria_network:
        aliases:
          - buscador-mongo
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 50M
        reservations:
          cpus: 0.25
          memory: 50M
  # es una imagen de postgresql para almacenar toda la data referida al proyecto y que sigue una estructura en concreto
  buscador-db:
    image: postgres:alpine3.17
    environment:
      - POSTGRES_PASSWORD=homito
    ports:
      - 6500:5432
    networks:
      pasionaria_network:
        aliases:
          - buscador-db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 50M
        reservations:
          cpus: 0.25
          memory: 50M
#  buscador-api: es el proyecto Java Spring Boot
  buscador-api:
    image: back-parcial:1.2
    ports:
      - 8080:8080
    environment:
#      postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://buscador-db/pasionaria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: homito
#      mongodb
      SPRING_DATA_MONGODB_DATABASE: pasionaria
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_URI: mongodb://buscador-mongo/docker-db
    networks:
      pasionaria_network:
        aliases:
          - buscador-api
    depends_on:
      - buscador-mongo
      - buscador-db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 250M
        reservations:
          cpus: 0.25
          memory: 80M
networks:
  pasionaria_network:
    name: pasionaria_net
    driver: bridge
    ipam:
      driver: default