version: "3.3"

services:
  buscador-ui:
    image: pasionaria-buscador
    ports:
      - 4200:80
  buscador-mongo:
    container_name: "mongodb"
    image: mongo
    ports:
      - 27017:27017
  buscador-selenium:
    container_name: "firefox"
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
  buscador-api:
    image: pasionaria-buscador-api
    ports:
      - 8080:8080
    depends_on:
      - buscador-mongo
      - buscador-selenium
